### ISSUE TITLE
Bot Down

### ISSUE THREAD

**Issue by CaptainAhoi** [HelleGazelle/teamsignal#1]
Mach den Bot wieder an!!

**Comment by SchulziWulzi** [comment]
![ts3client_win64_YOvyyDT1sJ](https://github.com/HelleGazelle/teamsignal/assets/75697831/895c1d06-792d-4c1a-83d8-d150200e610f)
Ich verliere hier kostbare Verräter Zeit!

**Comment by HelleGazelle** [comment]
Service restarted.
Bot erfolgreich getestet ✅
